export const ADD_ACTOR="ADD_ACTOR";
export const ADD_ACTOR_LOADING="ADD_ACTOR_LOADING";
export const ADD_ACTOR_ERROR="ADD_ACTOR_ERROR";
export const ADD_ACTOR_SUCCESS="ADD_ACTOR_SUCCESS"

export const GET_ALL_ACTOR="GET_ALL_ACTOR"
export const GET_ACTOR_SUCCESS="GET_ACTOR_SUCCESS";
export const GET_ACTOR_ERROR="GET_ACTOR_ERROR"

export const REMOVE_ACTOR="REMOVE_ACTOR";

export const GET_ACTOR="GET_ACTOR";

export const GET_NEW="GET_NEW";

export const EDIT_ACTOR="EDIT_ACTOR";




export const ADD_PRODUCER="ADD_PRODUCER";
export const ADD_PRODUCER_LOADING="ADD_PRODUCER_LOADING";
export const ADD_PRODUCER_ERROR="ADD_PRODUCER_ERROR";
export const ADD_PRODUCER_SUCCESS="ADD_PRODUCER_SUCCESS"

export const GET_ALL_PRODUCER="GET_ALL_PRODUCER"
export const GET_PRODUCER_SUCCESS="GET_PRODUCER_SUCCESS";
export const GET_PRODUCER_ERROR="GET_PRODUCER_ERROR"

export const REMOVE_PRODUCER="REMOVE_PRODUCER";

export const GET_PRODUCER="GET_PRODUCER";

export const EDIT_PRODUCER="EDIT_PRODUCER";




export const ADD_MOVIE="ADD_MOVIE";
export const ADD_MOVIE_LOADING="ADD_MOVIE_LOADING";
export const ADD_MOVIE_ERROR="ADD_MOVIE_ERROR";
export const ADD_MOVIE_SUCCESS="ADD_MOVIE_SUCCESS"

export const GET_ALL_MOVIE="GET_ALL_MOVIE"
export const GET_MOVIE_SUCCESS="GET_MOVIE_SUCCESS";
export const GET_MOVIE_ERROR="GET_MOVIE_ERROR"

export const REMOVE_MOVIE="REMOVE_MOVIE";

export const GET_MOVIE="GET_MOVIE";

export const EDIT_MOVIE="EDIT_MOVIE";


